version: '3.8'
services:
  db:
    image: postgres:15
    container_name: wordle-db
    environment:
      POSTGRES_DB: wordledb
      POSTGRES_USER: wordle
      POSTGRES_PASSWORD: wordle
    ports:
      - "5432:5432"
